en:
  title: "Huy Nguyen"
  subtitle: "I do things and sometimes I blog about it"
  description: "My personal website and blog documenting projects in regards to home lab, self-hosting and anything and everything of interest to me."
  keywords: [ "tech", "blog", "homelab", "self-hosted", "Artifical Intelligence", "Internet of Things", "Cloud", "Data Privacy", "Tech Tips and Tricks", "Software Development", "Tutorials", "Security" ]