contentTypeName: "blog"
dateFormat: "January 2, 2006"
rating: "general"
displayPagination: 5
archivePaginate: 365
showToc: true
rssfulltext: true
showReadingTime: true
shareLinks: true

taxonomy:
  tags: false
  category: true

# user defined
title: "Huy Nguyen"
subtitle: "I do things and sometimes I blog about it"
description: "My personal website and blog documenting projects in regards to home lab, self-hosting and anything and everything of interest to me."
keywords: [ "tech", "blog", "homelab", "self-hosted", "Artifical Intelligence", "Internet of Things", "Cloud", "Data Privacy", "Tech Tips and Tricks", "Software Development", "Tutorials", "Security" ]

author: "Huy Nguyen"
email: ""
contact: "https://keybase.io/sinicide/"

socials:
  - name: "Github"
    url: "https://github.com/sinicide/"
    title: "The codes"
    icon: "fab fa-github"
  - name: "Mastodon"
    url: "https://techhub.social/@sinicide"
    title: "The toots"
    icon: "fab fa-mastodon"
  - name: "Keybase"
    url: "https://keybase.io/sinicide/"
    title: "Verified!"
    icon: "fab fa-keybase"
  - name: "Threads"
    url: "https://www.threads.net/@sinicide"
    title: "The Threads"
    icon: "fa fa-at"
  - name: "BlueSky"
    url: "https://bsky.app/profile/sinicide.bsky.social"
    title: "BlueSkies"
    icon: "fa fa-cloud"

share:
  mastodon: false
  twitter: true
  threads: false
  bluesky: false
  facebook: true
  reddit: true
  linkedin: false
  email: false
  link: true