baseUrl: "https://huynguyen.me"
theme: "hugo-theme-hello-bulma"
pagination:
  pagerSize:
# robots.txt
enableRobotsTXT: true

module:
  mounts:
    - source: content
      target: content
      excludeFiles:
        - "templates/**"
