main:
  - identifier: "about"
    name: "About"
    url: "/"
    weight: 1
  - identifier: "blog"
    name: "Blog"
    url: "/blog"
    weight: 2
  - identifier: "categories"
    name: "Categories"
    url: "/categories"
    weight: 3
  - identifier: "archive"
    name: "Archive"
    url: "/archive"
    weight: 4