en:
  menuMore: "Show more"
  writtenBy: "Writte by"
  readMore: "Read more"
  readOtherPosts: "Read other posts"
  newerPosts: "Newer posts"
  olderPosts: "Older posts"
  minuteReadingTime: "minute read"
  dateFormatSingle: "2006-01-02"
  dateFormatList: "2006-01-02"
