dateFormat: "2006-01-02"
showMenuItems: 5
rssLimit: 15

github:
  user: "sinicide"
  contentRepo: "huynguyen-blog-content"

logo:
  logoText: "Huy Nguyen"
  logoHomeLink: "/"
  #or
  #path: "/img/your-example-logo.svg"
  #alt: "Your example logo alt text"

# Language
menuMore: "Show more"
writtenBy: "Writte by"
readMore: "Read more"
readOtherPosts: "Read other posts"
newerPosts: "Newer posts"
olderPosts: "Older posts"
minuteReadingTime: "minute read"
dateFormatSingle: "2006-01-02"
dateFormatList: "2006-01-02"